### ISSUE TITLE
Contestant那里只有一个字母在高亮区内

### ISSUE THREAD

**Issue by qinyihao** [tiger2005/CodeforcesContestHelper#11]
![image](https://user-images.githubusercontent.com/40647091/107143895-82686500-6972-11eb-9514-fa5131056c97.png)
就像这样（

**Comment by qinyihao** [comment]
typo

**Comment by tiger2005** [comment]
由于展开工具栏的时候再显示会产生挤压和溢出，这里的设计就是展开后显示一个字母以分清当前状态。
