### ISSUE TITLE
提交结果颜色建议

### ISSUE THREAD

**Issue by qz-cqy** [tiger2005/CodeforcesContestHelper#12]
![img](https://i.loli.net/2021/02/07/vrDWpxyFlKhXLNi.png)

（图片地址 https://i.loli.net/2021/02/07/vrDWpxyFlKhXLNi.png ）

如图是我过去的某场比赛的结果，其中红色加粗的 -5 看着总以为是 FST，希望可以改进。

**Comment by registerGen** [comment]
我也觉得这看着有点别扭。。。

改成灰色可能要好点

**Comment by qinyihao** [comment]
FST后期我们会进行特殊标记的（虽然现在不大会有人把这个工具开到比赛后1小时）

**Comment by qinyihao** [comment]
> ![img](https://camo.githubusercontent.com/571675988835c9212f654a90bb5d4bb8411ef45bfe31f2ea7d15bd42b8548f98/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30322f30372f76724457707879466c4b68584c4e692e706e67)
> 
> （图片地址 https://i.loli.net/2021/02/07/vrDWpxyFlKhXLNi.png ）
> 
> 如图是我过去的某场比赛的结果，其中红色加粗的 -5 看着总以为是 FST，希望可以改进。

好了的话我们会直接在这里comment并且close issue，届时请关注`main`分支上的内容，并进行重新下载，谢谢！（rui_er txdy!）

**Comment by qz-cqy** [comment]
谢谢 Orz

**Comment by tiger2005** [comment]
@qz-cqy @registerGen 实在很抱歉，由于这个功能需要爬取提交记录进行分析，在某些情况下会带来计算逻辑混乱和网络卡顿，所以只能统一改为灰色。之后我会想改进办法。

**Comment by tiger2005** [comment]
已经在最新版中完全修复问题。
