### ISSUE TITLE
Linux 下的字体问题

### ISSUE THREAD

**Issue by registerGen** [tiger2005/CodeforcesContestHelper#13]
![2021-02-07 22-18-28 的屏幕截图](https://user-images.githubusercontent.com/62944333/107149301-d2572400-6992-11eb-8ece-cf9cbfdcda52.png)

(Ubuntu 20.04 虚拟机)

希望能将某些部分的字体改成 Ubuntu Mono 之类的等宽字体，谢谢！

**Comment by qinyihao** [comment]
您能否安装一下[这里](https://github.com/tiger2005/CodeforcesContestHelper/tree/main/fonts)所有的.ttf格式的字体？谢谢qwq

**Comment by tiger2005** [comment]
没记错的话我已经通过 css/client.css 进行导入。可以加我的 QQ (3478556308) 进行沟通。

**Comment by tiger2005** [comment]
已经加入字体全家桶。

**Comment by registerGen** [comment]
已经解决了，谢谢
