### ISSUE TITLE
Please show the name of the problems in each contest,

### ISSUE THREAD

**Issue by Alexwei172** [tiger2005/CodeforcesContestHelper#17]
**Please show the name of the problems in each contest,**
![image.png](https://i.loli.net/2021/02/08/LahMO4o62nfr1tV.png)

**Comment by qinyihao** [comment]
> **Please show the name of the problems in each contest,**
> ![image.png](https://camo.githubusercontent.com/7e096853e223dc1a6e00389a5915def2973c8581dd95c04d534954188d35195a/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30322f30382f4c61684d4f346f36326e66723174562e706e67)

No it's hard to do that

**Comment by qinyihao** [comment]
It's now in our queue
