### ISSUE TITLE
显示当前时刻所能得到的分数

### ISSUE THREAD

**Issue by HyyypRtf06** [tiger2005/CodeforcesContestHelper#18]
针对于即时比赛，显示当前时刻每道题目还能得到的分数。（大概是为了方便自己中途改变开题顺序？）  
至于 VP 直接忽略吧……  
感觉这个功能必要性不是很大？可选择开发（如果有可能实现）。

**Comment by qinyihao** [comment]
应该会进行开发的，现在暂时in queue

**Comment by qinyihao** [comment]
好了（

**Comment by tiger2005** [comment]
已经在 dev 更新。
