### ISSUE TITLE
Bug when switching between light mode and dark mode on macOS

### ISSUE THREAD

**Issue by 23786** [tiger2005/CodeforcesContestHelper#19]
Hello! I am using the CCH on macOS 11.1. At first, I was using dark mode, and the app looks pretty well.

![Dark](https://user-images.githubusercontent.com/63693525/107228402-9934b780-6a57-11eb-8f8b-a6b545819a66.jpg)

But when I tried to switch from dark mode to light mode, the app displayed something unexpected. Some of the controls on the window still had a black background color:

<img width="1080" alt="Light" src="https://user-images.githubusercontent.com/63693525/107228629-d305be00-6a57-11eb-993a-3e67be0927fe.png">

Maybe this is a bug? I am using `nwjs` provided in the QQ group.

**Comment by qinyihao** [comment]
> Hello! I am using the CCH on macOS 11.1. At first, I was using dark mode, and the app looks pretty well.
> 
> ![Dark](https://user-images.githubusercontent.com/63693525/107228402-9934b780-6a57-11eb-8f8b-a6b545819a66.jpg)
> 
> But when I tried to switch from dark mode to light mode, the app displayed something unexpected. Some of the controls on the window still had a black background color:
> 
> <img alt="Light" width="1080" src="https://user-images.githubusercontent.com/63693525/107228629-d305be00-6a57-11eb-993a-3e67be0927fe.png">
> 
> Maybe this is a bug? I am using `nwjs` provided in the QQ group.

So you need to click on the button here as provided in the pic:
![image](https://user-images.githubusercontent.com/40647091/107229126-62ab6c80-6a58-11eb-9578-98ee5baed344.png)

**Comment by qinyihao** [comment]
![image](https://user-images.githubusercontent.com/40647091/107229816-3c3a0100-6a59-11eb-8f92-32e8889dc278.png)

**Comment by qinyihao** [comment]
Please, send a screenshot of the first 10 lines of /css/default.css onto this issue, thanks.

It's for dev purposes.

**Comment by qinyihao** [comment]
@23786

**Comment by 23786** [comment]
@qinyihao

![](https://tva1.sinaimg.cn/large/008eGmZEgy1gnghnbrb87j31bx0u0n30.jpg)

**Comment by tiger2005** [comment]
已解决
