### ISSUE TITLE
用户名不能带有“-”

### ISSUE THREAD

**Issue by henrytbtrue** [tiger2005/CodeforcesContestHelper#2]
RT，用户名带有"-"的时候会显示 Username Incorrect

**Comment by henrytbtrue** [comment]
另外Incorrect好像拼错了

**Comment by registerGen** [comment]
例如：

![image](https://user-images.githubusercontent.com/62944333/106721790-18815000-6640-11eb-87f6-bff0ab2b028a.png)

**Comment by tiger2005** [comment]
> RT，用户名带有"-"的时候会显示 Username Incorrect

我设置的限制是 [a-zA-Z0-9._] ，漏掉 - 真的很抱歉。

另外，如果还有其他的允许字符的话请务必告诉我

**Comment by henrytbtrue** [comment]
谢谢！

**Comment by tiger2005** [comment]
@henrytbtrue  @registerGen 控制代码在 js/client.js 的第 587 行，可以随时修改。

我将会在稍后更新代码。

**Comment by tiger2005** [comment]
更新完毕。
