### ISSUE TITLE
最小化至托盘 & 查看好友排名

### ISSUE THREAD

**Issue by HyyypRtf06** [tiger2005/CodeforcesContestHelper#8]
RT。原来的窗口还是太大了，个人觉得最小化至托盘比较方便随时查看。

另外，希望能实时查看好友排名？

**Comment by tiger2005** [comment]
第一个的话这个功能似乎已经被 NW.js 废除了。
第二个的话可以直接输入好友名字进行查询。如果是想同时显示多个用户的话我会考虑接着开发。

**Comment by qinyihao** [comment]
第一个的话，后期我们可以在搭建的时候把相应行去掉来解决。

**Comment by qinyihao** [comment]
其实第二个可以通过开虚拟机，用多开app来实现

**Comment by qinyihao** [comment]
@HyyypRtf06 
> 另外，希望能实时查看好友排名？

您的意思是要与您的好友在赛时进行比拼吗？

**Comment by qinyihao** [comment]
多开已完成

**Comment by HyyypRtf06** [comment]
> @HyyypRtf06
> 
> > 另外，希望能实时查看好友排名？
> 
> 您的意思是要与您的好友在赛时进行比拼吗？

是，相当于一个 standing。(避免一个个输入好友名字的麻烦)

**Comment by qinyihao** [comment]
> > @HyyypRtf06
> > > 另外，希望能实时查看好友排名？
> > 
> > 
> > 您的意思是要与您的好友在赛时进行比拼吗？
> 
> 是，相当于一个 standing。(避免一个个输入好友名字的麻烦)

好的了解了，我们会尽量实现的

**Comment by qinyihao** [comment]
@HyyypRtf06 
![7149B995-0C60-4C9A-984D-7DA7C58B4B91](https://user-images.githubusercontent.com/40647091/107134906-24fff400-6931-11eb-965b-44b7577f8295.png)

这种样式可以吗

**Comment by qinyihao** [comment]
> @HyyypRtf06
> ![7149B995-0C60-4C9A-984D-7DA7C58B4B91](https://user-images.githubusercontent.com/40647091/107134906-24fff400-6931-11eb-965b-44b7577f8295.png)
> 
> 这种样式可以吗

这种其实比较难实现

**Comment by HyyypRtf06** [comment]
> @HyyypRtf06
> ![7149B995-0C60-4C9A-984D-7DA7C58B4B91](https://user-images.githubusercontent.com/40647091/107134906-24fff400-6931-11eb-965b-44b7577f8295.png)
> 
> 这种样式可以吗

qaq 换个图床吧我这里显示不出来(为什不用 gitee 呢(bushi))

**Comment by qinyihao** [comment]
> > @HyyypRtf06
> > ![7149B995-0C60-4C9A-984D-7DA7C58B4B91](https://user-images.githubusercontent.com/40647091/107134906-24fff400-6931-11eb-965b-44b7577f8295.png)
> > 这种样式可以吗
> 
> qaq 换个图床吧我这里显示不出来(为什不用 gitee 呢(bushi))

https://github.com/googlehosts/hosts/blob/master/hosts-files/hosts

所有内容copy到

C:\Windows\System32\drivers\etc\hosts

**Comment by qinyihao** [comment]
> > @HyyypRtf06
> > ![7149B995-0C60-4C9A-984D-7DA7C58B4B91](https://user-images.githubusercontent.com/40647091/107134906-24fff400-6931-11eb-965b-44b7577f8295.png)
> > 这种样式可以吗
> 
> qaq 换个图床吧我这里显示不出来(为什不用 gitee 呢(bushi))

我有GitHub pro，但是gitee总限制tgb（

**Comment by HyyypRtf06** [comment]
> > @HyyypRtf06
> > ![7149B995-0C60-4C9A-984D-7DA7C58B4B91](https://user-images.githubusercontent.com/40647091/107134906-24fff400-6931-11eb-965b-44b7577f8295.png)
> > 这种样式可以吗
> 
> 这种其实比较难实现

其实我觉得样式没什么大问题，不要和 UI 风格差别太大即可。关键是只要能实现且兼顾效率，就非常令人敬佩。

**Comment by qinyihao** [comment]
> > > @HyyypRtf06
> > > ![7149B995-0C60-4C9A-984D-7DA7C58B4B91](https://user-images.githubusercontent.com/40647091/107134906-24fff400-6931-11eb-965b-44b7577f8295.png)
> > > 这种样式可以吗
> > 
> > 
> > 这种其实比较难实现
> 
> 其实我觉得样式没什么大问题，不要和 UI 风格差别太大即可。关键是只要能实现且兼顾效率，就非常令人敬佩。

ok，现在正在重写大部分的代码，所以预计耗时较长，好了的话我会at您并且close issue的。

**Comment by qinyihao** [comment]
@HyyypRtf06 请在dev分支测试一下新版本，如果可以满足的话我就进行merge操作了。

**Comment by qinyihao** [comment]
@HyyypRtf06 

最下面cmp输入要与其比拼的人
![image](https://user-images.githubusercontent.com/40647091/107143291-4c75b180-696f-11eb-8d50-7155fcbb0290.png)

```
C -> CONTESTANT
O -> OUT_OF_COMPETITION
V1 -> 第一场 VIRTUAL
V-1 -> 倒数第一场 VIRTUAL
```

**Comment by qinyihao** [comment]
@HyyypRtf06 我这边先merge，有任何问题请新开一个issue，谢谢！

**Comment by HyyypRtf06** [comment]
好的。今晚正好有 CF 我测试一下。



---原始邮件---
发件人: "qinyihao"<notifications@github.com&gt;
发送时间: 2021年2月7日(周日) 晚上6:10
收件人: "tiger2005/CodeforcesContestHelper"<CodeforcesContestHelper@noreply.github.com&gt;;
抄送: "HyyypRtf06"<1535608215@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [tiger2005/CodeforcesContestHelper] 最小化至托盘 &amp; 查看好友排名 (#8)




 
@HyyypRtf06 我这边先merge，有任何问题请新开一个issue，谢谢！

**Comment by HyyypRtf06** [comment]
感谢。使用起来非常爽，没有问题（别忘更新 wiki qwq）。

**Comment by qinyihao** [comment]
> 感谢。使用起来非常爽，没有问题（别忘更新 wiki qwq）。

ok，感谢测试
